### ISSUE TITLE
AWS (not S3?) credentials needed

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/aicoe-osc-demo#161]
This cell in the pdf_text_extraction notebook names a credential I don't have (it uses AWS_ instead of S3_ prefixes):

```
# init s3 connector
s3c = S3Communication(
    s3_endpoint_url=os.getenv("S3_ENDPOINT"),
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    s3_bucket=os.getenv("S3_BUCKET"),
)
```

May I please have the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY secrets?  Thanks!

@JeremyGohBNP for visibility

**Comment by JeremyGohBNP** [comment]
Hi Michael, the names of the secrets (AWS_XX) were given to me in the new credentials.env file sent by Erik (after the security incident). I did not change them, hence the code using these names. There seems to be some variety in credentials names, because the initial version I had was with S3_XX. Are there standard names we should use? I just modified the code from S3_XX to AWS_XX when I received the new set of credentials, you might just need to change them back locally to S3_XX if yours are named this way.

**Comment by MichaelTiemannOSC** [comment]
This fixed it for me:

```
# init s3 connector
s3c = S3Communication(
    s3_endpoint_url=os.getenv("S3_ENDPOINT"),
    aws_access_key_id=os.getenv("S3_LANDING_ACCESS_KEY"),
    aws_secret_access_key=os.getenv("S3_LANDING_SECRET_KEY"),
    s3_bucket=os.getenv("S3_BUCKET"),
)
```
