### ISSUE TITLE
Update the user workflow around pdf selection

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#192]
The NLP demo is to be transitioned into a public tool and it should have a user friendly workflow around which PDFs are used for training and inference.
Based on the discussion in the email, here's what I gathered has to be implemented:

- The user is shown a list of PDFs to select from 
- The selected PDFs are then moved to a new experiment location 
- The inference pipeline runs with the selected pdfs

Questions
- Do we also want to have this option of selecting PDFs for the training pipeline? In that case, the user would presumably give an annotation file as well.
- The architecture diagram also read "the user logs on to a tool and selects the pdfs" What kind of tool do you have in mind for this process? The easiest way to implement is to have a notebook with widgets that the user can tweak. The other, more involved way is to have a demo flask application. 

Let me know your thoughts on this @JeremyGohBNP @erikerlandson @MichaelTiemann

**Comment by MichaelTiemannOSC** [comment]
There are two use cases for PDF selection: training and extraction.  In the case of training, the user should be selecting an annotations file (which might then show the user the PDFs that will be used for training).  In the case of extraction, the user should be able to select the PDFs directly.  The annotations file should have some helpful metadata so that when users are selecting from annotations files, they know the region/sector/KPIs being trained by that annotations file.

As we organize our PDF source files, we should be getting metadata that includes region (US vs. EU vs APAC, etc), sector (Utilities vs Steel vs Automotive etc), and perhaps other factors.  It would be great to give users options to initially select according to some metadata criteria, and then check/uncheck additional files, and then name that selection as an EXPERIMENT_NAME.

**Comment by JeremyGohBNP** [comment]
Indeed, training and extraction would be 2 separate pipelines - the priority would be the extraction pipeline though. That being said, it does not hurt to implement the training pipeline simultaneously. Here is my vision: 
- Extraction: the user enters a company (either ID, name, or other characteristics like region, sector mentioned by Michael) ; he gets a list of PDFs to select from. If no one is relevant, he can upload the PDF he wants to perform extraction on.
- Training: firsts, the user has to upload an annotation file (previously created). Then, he either uploads the corresponding PDF file (i.e. for which the annotations were made) or select it if it is already stored on the S3 bucket. UI-wise, it's pretty similar to the extraction case but loading an annotation file serves as a trigger to select or upload PDFs instead of entering a company name or ID

As for "logs on to a tool", I meant "login to the platform and its data extraction services". I would lean towards a Flask application rather than a Notebook because non-technical people might be deterred from using the tools if they have to navigate a Notebook (and see some code).

**Comment by Shreyanand** [comment]
Addressed in #196
