### ISSUE TITLE
Remove pipfile-requirements manager from .thoth.yaml

### ISSUE THREAD

**Issue by shreekarSS** [os-climate/aicoe-osc-demo#207]
**Describe the bug**

The pipfile-requirements manager can be removed because requirements.txt isn’t being utilized for packaging or deployment. Only the Pipfile.lock is needed for deployment info.
Else Kebechet's Update manager will not work on this aicoe-osc-demo repo

**To Reproduce**
1. Create an issue with title  'Kebechet update'
2. Kebechet's pipfile-requirements manager will fail with creating new issue like https://github.com/shreekarSS/aicoe-osc-demo/issues/2

**Expected behavior**
Once Update manager runs successfully, it will raise a PR like https://github.com/shreekarSS/aicoe-osc-demo/pull/3

**Comment by codificat** [comment]
Actually, the pipfile-requirements manager failure like https://github.com/shreekarSS/aicoe-osc-demo/issues/2 might be a bug in Kebechet, as I believe that the mentioned `Pipfile` entry could be translated to a `requirements.txt` entry.

Nevertherless, it's probably a good idea to remove that manager from this repo's configuration, as you say, because there is no `requirements.txt` here and it doesn't seem to be needed.
