### ISSUE TITLE
Couldn't add kubeflow pipeline runtime configuration

### ISSUE THREAD

**Issue by Jeevi281** [os-climate/aicoe-osc-demo#228]
**Describe the bug**

I couldn't able to add kubeflow runtime to run the pipeline.  

**To Reproduce**

1. After creating the pipline like this

![Screenshot (209)](https://user-images.githubusercontent.com/116078421/199672887-3b5b7149-52a3-4810-82bc-bdaaa6a9d2ee.png)

2. Go to 'runtime' on the left side bar
3. Click on ' + icon' on right upper corner
4. Select 'New Kubeflow Pipeline runtime configuration' 
5. After entering all the details to create runtime, click save & close

![Screenshot (211)](https://user-images.githubusercontent.com/116078421/199673499-31e8f5ab-d051-4e93-8ffa-177e4dab1ecc.png)

6. Still the runtime is not added here
![Screenshot (213)](https://user-images.githubusercontent.com/116078421/199673774-6910cafc-e4fb-4803-a782-a67e98553a20.png)

**Expected behavior**

If the runtime is added, I can be able to run the pipeline

**Screenshots**

**Additional context**

**Comment by Jeevi281** [comment]
@Shreyanand

**Comment by schwesig** [comment]
see also YouTube comment:
https://www.youtube.com/watch?v=lGeT615YNlM&lc=UgxmpMwWqw-345wvcRx4AaABAg

**Comment by Shreyanand** [comment]
Thanks for adding the details @Jeevi281. It seems that the cloud object storage and password are not added in the configuration. In the [docs](https://github.com/os-climate/aicoe-osc-demo/blob/master/docs/elyra-pipeline.md#add-kubeflow-pipeline-runtime-configuration) there is an example. 
Do you have credentials for any s3 bucket that you could use? If not, you could create an issue [here](https://github.com/os-climate/OS-Climate-Community-Hub/issues/new?assignees=erikerlandson&labels=Bucket-credentials&template=request-credentials-for-an-os-climate-bucket.md&title=Request+credentials+for+an+os-climate+bucket) to get the credentials for the os-climate bucket.

**Comment by Jeevi281** [comment]
Thanks @Shreyanand. I added the configuration as you said, the runtime is added now. Though, I couldn't able to see status in run details 

**To Reproduce**
1. After clicking run pipeline with the created kubeflow pipeline configuration, the below dialogue box is popped.

![Screenshot (225)](https://user-images.githubusercontent.com/116078421/200494222-202b4b46-f3da-45be-87ad-44ef73ba0754.png)

2. Click 'Run Details'
3. The below screen will appear.
![Screenshot (223)](https://user-images.githubusercontent.com/116078421/200493546-20d3012a-7382-4801-ae09-fea05fe9722b.png)

**Expected Behaviour**
To be able to see run details

**Comment by MichaelTiemannOSC** [comment]
What's happening here is that *.cluser.local is entirely within the kubeflow world--there's no externally valid route point.  There are various services that can peer into the kubeflow world and report things out--especially if you have admin privs.  But generally speaking, the environments of the images you create and run are not publicly visible.

There is a whole paradigm around how these pipelines operate which is really quite different than the conventional Unix pipeline (e.g. `tool1 | tool2 | tool3` all operating in a consistent, persistent environment).

Separately, and especially to any AI-CoE team members reading this: #115 .  Please, let's fix our templates, documentation, etc., so that we don't wind up with literally thousands of junk execution runs in the top-level of the bucket intended for landing data for all to use.

**Comment by Shreyanand** [comment]
The UI dashboard for kubeflow is available at this [location](https://ml-pipeline-ui-kubeflow.apps.odh-cl2.apps.os-climate.org/#/runs). You can track your runs here. The *.cluster.local endpoint used in the configuration is internal and the Elyra UI uses that to generate the alert box and so it leads to page not found.

**Comment by Jeevi281** [comment]
Resolved! Thanks @Shreyanand @MichaelTiemannOSC
