### ISSUE TITLE
Access to GPU Server

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/aicoe-osc-demo#249]
@Shreyanand 
 
Unfortunately we have no access to our gpu server anymore and we cannot test the question from Shiming.
 
I now checked on the cluster, but I see that if I start a server on the cl2 then i have no possibility to “log out” of the container, that means I can not run docker to check Shimings issue.
 
Now the question is, can you check if the Dockerfile has issues or is there a possibility that I test and configure the file? With that I mean I would need commands like podman run, build, ps and so on. On our old server someone installed podman for us 😊 and I have not much knowledge about server architecture.
 
Please let me know if my questions make new questions.
 
If one of the others has an idea, feel also free to answer 😉. It is important to answer the question from Shiming before we go public, because otherwise we publish code which may not run.
 
Thanks and best regards,
 
@DaBeIDS

**Comment by DaBeIDS** [comment]
Hi all,
sorry that was missleading formulated in my mail. With "our gpu server" i meant the server with gpu access on Allianz side was decommissioned and i only wanted to see if we can also test docker files on the cluster in some way to answer Shimings question about the docker file. The OSC cluster gpu server are all fine.

@HeatherAck I think we can close the issue here and may open an issue ticket with "Docker file may not work", but better in the corporate_data_extraction repo.

Best regards,

David
