### ISSUE TITLE
Storing data locally in data/raw subdirectory is invisible to Notebook's GitHub 

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/aicoe-osc-demo#32]
**Describe the bug**
I've uploaded a file to the data/raw directory in the file tree rooted in my clone of the aicoe template at https://github.com/MichaelTiemannOSC/osc-ingest-sample_corp_data/

However, no GitHub actions are available for that file, and it does not show up as anything wihin my Git view.  The notebook file I have created in the notebook/ subdirectory is perfectly visible to Git, with visible options to start tracking that file.

**To Reproduce**
1. Clone repository from https://github.com/aicoe-aiops/project-template/generate
2. Inside Elyra notebook, clone the repository
3. Visit root of repository in Git plugin
4. Drill down to data/raw directory
5. Upload a file

**Expected behavior**
I expect that adding a file anywhere in the repository tree will encourage Git to advertise that I can start tracking changes to that file and that once I do, I can commit to the repository.

**Screenshots**
N/A

**Additional context**
I'm going to go ahead and check in that file to Git using web-based interface and pull the data down from there (hopefully).

**Comment by MichaelClifford** [comment]
Hi @MichaelTiemannOSC , this is actually the expected behavior of the template. The idea here is that the code for either generating or accessing the data is stored in git, but the data itself is not. To that end we add the data directory to our [.gitignore](https://github.com/aicoe-aiops/project-template/blob/53fa1033b3aaf8648af4cc845dabfc023d526f8e/.gitignore#L78-L79) file. I think  this is a reasonable pattern for most use cases. But, if you would like to override this behavior for a specific dataset, you can use `git add FILE_NAME --force` to make sure it gets tracked and added to the remote repo. 

Let me know if you have any other questions on this : )

**Comment by MichaelTiemannOSC** [comment]
That will teach me to read the docs and source more carefully the next time.  Thanks!

**Comment by MichaelClifford** [comment]
:+1: Also an indication to us that we can probably improve the template's docs. Thanks!
