### ISSUE TITLE
Fix the incorrect model output

### ISSUE THREAD

**Issue by Shreyanand** [os-climate/aicoe-osc-demo#92]
The current work in progress part of the pipeline is to add inference notebook to the pipeline (tracked in issues #88 #84).   While running the inference notebook on the sample pdfs from Equinor and other companies, we observed that the model outputs the label '0' for most cases. 

In all, we have 24 kpi questions. When we run the inference with all of them, for 23 questions the model finds no relevant paragraph, i.e., assigns a 0 label to all the paragraphs. For the one question, ""What is the company name", it finds several hundred paragraphs as relevant and stores that in the output csv.

According to the output [csv](https://github.com/os-climate/corporate_data_pipeline/blob/main/Allianz_NLP/data/infer/RELEVANCE/ESG/Text/sustainability-report-2019_predictions_relevant.csv), it doesn't seem like the desired and the correct output. Following are the kpi_mapping file used and the predicted output.

[kpi_mapping file](https://github.com/os-climate/aicoe-osc-demo/files/7486672/kpi_mapping_all.csv)
[Predicted outputs file](https://github.com/os-climate/aicoe-osc-demo/files/7486674/sustainability-report-2019_predictions_relevant.csv)

To reproduce the bug follow these instructions:

- Sign in to https://jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org/
- Select AICoE OSC demo image with Large memory and 1 GPU
- Run the pdf extraction notebook to extract text from pdfs
- Run the infer relevance notebook and see the model run logs
- Check the `data/infer` directory to see the model output

cc @chauhankaranraj @ChristianMeyndt

**Comment by MichaelClifford** [comment]
@Shreyanand can you add instructions on how someone could recreate the current bug on the os-c cluster?

**Comment by ChristianMeyndt** [comment]
Hi @Shreyanand,

currently I'm not able to start an AICoE OSC demo image in Jupyterhub, most probably because of insufficient resources. It sais:  [Warning] 0/14 nodes are available: 3 Insufficient nvidia.com/gpu, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 5 Insufficient cpu, 6 node(s) didn't match Pod's node affinity.

But I made some thoughts about this problem:
I think actually we had never really tested to use this config parameter "kpi_questions". So I can not really say if this works on our side.
As we use the kpi_mapping.csv as a mandatory input for the KPI inference, we usually only changed this file.

So this would be another good test: What happens if you adjust the kpi_mapping.csv, so that it only contains the four KPIs 9 - 12?
I will try that when I'm able to start the image on my side. If not, then maybe you can test that too.

cc @MichaelClifford @chauhankaranraj 

Thanks,
Christian

**Comment by chauhankaranraj** [comment]
> currently I'm not able to start an AICoE OSC demo image in Jupyterhub, most probably because of insufficient resources. It sais: [Warning] 0/14 nodes are available: 3 Insufficient nvidia.com/gpu, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 5 Insufficient cpu, 6 node(s) didn't match Pod's node affinity.

I'm not fully sure, but it could be the case that the cluster is failing to spawn coz you've requested multiple gpus. Could you try requesting only 1 gpu and see if that helps?

> So this would be another good test: What happens if you adjust the kpi_mapping.csv, so that it only contains the four KPIs 9 - 12?
> I will try that when I'm able to start the image on my side. If not, then maybe you can test that too.

We did try adjusting the csv to have only those 4 kpis, and the result was the same (empty dataframe). Which is consistent with our previous observation i.e. when we used all 24 kpis, the results contained answers (relevant paragraphs) only for the first one ("What is the company name?").

**Comment by ChristianMeyndt** [comment]
I was able now to start the image with the correct size.
But I'm getting now an error when trying to import the sources in the notebook (from src.components.preprocessing import Extractor).
Inside it tries to download the file kpi_mapping.csv from s3 and it stops with the following error: 
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
Did you also see such an error?

**Comment by ChristianMeyndt** [comment]
Was a problem with my credentials.env file...I'm able now to run the notebook and will let you know when i found something.

**Comment by ChristianMeyndt** [comment]
In order to run the infer_relvence notebook in JupyterHub we had to change config_farm_train.py:
line 
self.root = str(pathlib.Path(src.__file__).resolve().parent.parent ) 
had to be changed to 
self.root = str(pathlib.Path(__file__).resolve().parent.parent.parent )

We changed noothing else in the notebook and we did get meaningful examples as expected.
You can see in the mentioned example in the notebook (but also in the output files):
![image](https://user-images.githubusercontent.com/69670279/141323788-83fb2fd3-d057-4fd2-a461-b73edaed9db8.png)
It shows that the relevance detection calssifies the sentence as relevant with a probability > 73%, which makes sense.
On your side it seems that on your side the same example was classified as not relevant with a high probability.

So I think it totally makes sense to have session together again to find out where the differences come from.
@MichaelClifford @Shreyanand @chauhankaranraj

**Comment by Shreyanand** [comment]
> In order to run the infer_relvence notebook in JupyterHub we had to change config_farm_train.py: line self.root = str(pathlib.Path(src.**file**).resolve().parent.parent ) had to be changed to self.root = str(pathlib.Path(**file**).resolve().parent.parent.parent )

Good catch! We fixed this in the latest [PR](https://github.com/os-climate/aicoe-osc-demo/pull/101). The PR also adds the kpi extraction inference [notebook](https://github.com/os-climate/aicoe-osc-demo/blob/master/notebooks/demo2/infer_kpi.ipynb) that works as expected. 


> We changed noothing else in the notebook and we did get meaningful examples as expected. You can see in the mentioned example in the notebook (but also in the output files): ![image](https://user-images.githubusercontent.com/69670279/141323788-83fb2fd3-d057-4fd2-a461-b73edaed9db8.png) It shows that the relevance detection calssifies the sentence as relevant with a probability > 73%, which makes sense. On your side it seems that on your side the same example was classified as not relevant with a high probability.

This is very interesting. Did you use the notebook code to download the same model we used (the one stored in s3)? And are you using a https://jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org/ instance to run the notebook?

**Comment by ChristianMeyndt** [comment]
Yes, I only used code from the infer_relevance notebook, also for the download of the model from s3 and ran it on a https://jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org/ instance.

**Comment by chauhankaranraj** [comment]
> Yes, I only used code from the infer_relevance notebook, also for the download of the model from s3 and ran it on a https://jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org/ instance.

Thanks @ChristianMeyndt, I can confirm I get the same result for the "prediction on single example", and I also see some relevant results for kpis 9-12 when I run it on the Equinor sample pdf :) Seems like updating the path fixes the issue.

**Comment by Shreyanand** [comment]
@chauhankaranraj @ChristianMeyndt, I see the same behavior after the latest changes. These changes also update the version of ML packages (farm, torch, and mmcv) which could also be a reason for seeing the desired results. 
Since it's fixed, I'm closing this issue. Thanks all for debugging it :)
